import streamlit as st
from agent import Agent

# 1. Page Configuration
st.set_page_config(
    page_title="Philosopher AI Agent",
    page_icon="🤖",
    layout="wide"
)

# 2. Maintain Persistent Agent and Chat State across UI re-runs
if "agent" not in st.session_state:
    st.session_state.agent = Agent()

if "ui_chat_history" not in st.session_state:
    st.session_state.ui_chat_history = []

# 3. Sidebar Panel (Perfect for showing off your IR features to the grader!)
with st.sidebar:
    st.title("⚙️ Agent Controls")
    st.markdown("Use these configurations to alter the Information Retrieval and styling tracks.")
    st.markdown("---")
    
    # 🎯 Interactive toggle for Philosopher Mode
    philosopher_mode = st.toggle(
        "🧠 Enable Philosopher Mode", 
        value=False,
        help="Forces the agent to reformulate queries and reply exclusively in historical quotes."
    )
    
    st.markdown("---")
    st.subheader("📝 Live Long-Term Memory Summary")
    st.info("This is the core summarized profile generated by the agent's memory compaction loop:")
    
    # Live updates of your compacted memory state!
    current_summary = st.session_state.agent.memory.summary
    if current_summary:
        st.caption(current_summary)
    else:
        st.caption("*Memory summary is currently empty. Start chatting to populate and trigger compaction!*")

# 4. Main Chat Workspace
st.title("🤖 Advanced IR Agent Workspace")
st.markdown("This agent utilizes tiered short-term context, vector DB lookup via ChromaDB, and web search routing.")

# Render existing messages elegantly
for msg in st.session_state.ui_chat_history:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# 5. Handle Live User Chat Input
if user_query := st.chat_input("Ask your agent a question..."):
    
    # Display user's message instantly in the UI
    with st.chat_message("user"):
        st.markdown(user_query)
    st.session_state.ui_chat_history.append({"role": "user", "content": user_query})
    
    # Run the agent through its background memory and web search pipelines
    with st.spinner("Agent thinking & retrieving context..."):
        # We pass the toggle state directly into your existing agent class!
        agent_response = st.session_state.agent.chat(user_query, philosopher_mode=philosopher_mode)
        
    # Display the agent's structured response
    with st.chat_message("assistant"):
        st.markdown(agent_response)
    st.session_state.ui_chat_history.append({"role": "assistant", "content": agent_response})
    
    # Force the sidebar to update immediately if memory compaction happened
    st.rerun()